"""Anomaly alert digest generator for operational reporting."""

import pandas as pd


def generate_markdown_digest(anomaly_df: pd.DataFrame, city: str) -> str:
    """Generate a Markdown operational summary of recent anomalies.

    Args:
        anomaly_df: DataFrame containing only the anomaly records.
        city: The name of the city the anomalies belong to.

    Returns:
        A Markdown formatted string summarizing the anomalies.
    """
    if anomaly_df.empty:
        return f"# 🟢 Anomaly Alert Digest: {city}\n\n**Status:** All Clear\nNo operational anomalies detected in the selected time window.\n"

    n_anomalies = len(anomaly_df)
    n_surges = sum(anomaly_df["anomaly_type"] == "surge")
    n_dips = sum(anomaly_df["anomaly_type"] == "dip")

    md = [
        f"# 🚨 Anomaly Alert Digest: {city}",
        "",
        f"**Summary:** Detected **{n_anomalies}** total anomaly events ({n_surges} surges, {n_dips} dips).",
        "",
        "## Detailed Events",
        "",
    ]

    for _, row in anomaly_df.sort_values("date", ascending=False).iterrows():
        date_str = row["date"].strftime("%Y-%m-%d") if pd.notnull(row["date"]) else "Unknown Date"
        a_type = str(row["anomaly_type"]).upper()
        icon = "📈" if a_type == "SURGE" else "📉" if a_type == "DIP" else "⚠️"

        md.append(f"### {icon} {a_type} on {date_str}")
        md.append(f"- **Severity Score:** `{row.get('anomaly_score', 0):.2f}`")
        md.append(f"- **Actual Orders:** `{row.get('orders', 0):.1f}`")
        md.append(f"- **Expected Orders:** `{row.get('pred_orders', 0):.1f}`")
        md.append(f"- **Deviation:** `{row.get('residuals', 0):+.1f}` orders")
        md.append("")

    md.append("---\n*Generated by DemandIQ Automated Reporting*")
    return "\n".join(md)
